PREFIX rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dcterms:	<http://purl.org/dc/terms/>
PREFIX skos:	<http://www.w3.org/2004/02/skos/core#>
PREFIX owl:	<http://www.w3.org/2002/07/owl#>
PREFIX foaf:	<http://xmlns.com/foaf/0.1/>
PREFIX crm:	<http://www.cidoc-crm.org/cidoc-crm/>
PREFIX geo:	<http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX kid:	<http://kerameikos.org/id/>
PREFIX kon:	<http://kerameikos.org/ontology#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX spatial: <http://jena.apache.org/spatial#>

SELECT DISTINCT ?uri ?label WHERE { 
  {
    SELECT (?facet as ?uri) ?label WHERE {
      %STATEMENTS%
      ?facet skos:prefLabel ?label
      }
    }
  UNION {
    SELECT (?match as ?uri) ?label WHERE {
      %STATEMENTS%
      ?match skos:exactMatch ?facet ;
                        skos:prefLabel ?label
      }
    }
  FILTER langMatches(lang(?label), "en") 
} ORDER BY ?label