PREFIX rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dcterms:	<http://purl.org/dc/terms/>
PREFIX skos:	<http://www.w3.org/2004/02/skos/core#>
PREFIX owl:	<http://www.w3.org/2002/07/owl#>
PREFIX foaf:	<http://xmlns.com/foaf/0.1/>
PREFIX crm:	<http://www.cidoc-crm.org/cidoc-crm/>
PREFIX geo:	<http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX kid:	<http://kerameikos.org/id/>
PREFIX kon:	<http://kerameikos.org/ontology#>
PREFIX edm:	<http://www.europeana.eu/schemas/edm/>

CONSTRUCT {?object a crm:E22_Man-Made_Object ;
            dcterms:title ?title ;
            dcterms:identifier ?id ;
            dcterms:publisher ?keeper; 
            crm:P138i_has_representation ?representation ;
            crm:P129i_is_subject_of ?manifest .
          ?representation dcterms:format ?format ;
            dcterms:conformsTo ?conformsTo} WHERE {
%STATEMENTS%
?object crm:P1_is_identified_by ?id1 ;
    crm:P1_is_identified_by ?id2 .
?id1 a crm:E33_E41_Linguistic_Appellation ;
    crm:P190_has_symbolic_content ?title .
?id2 a crm:E42_Identifier ;
    crm:P190_has_symbolic_content ?id .
OPTIONAL {?object crm:P50_has_current_keeper/skos:prefLabel ?keeper FILTER (langMatches(lang(?keeper), "en"))} 
OPTIONAL {?object crm:P138i_has_representation ?representation
	OPTIONAL {?representation dcterms:format ?format}
	OPTIONAL {?representation dcterms:conformsTo ?conformsTo}}
OPTIONAL {?object crm:P129i_is_subject_of ?manifest}
}